<?php
function getReasonValue()
{
	$reasonValue =array(1=>"Inquire Voxiant's services",
		"Get a quote for Brand Identity creation",
		"Get a quote for Marketing Solution",
		"Get a quote for Website Solution",
		"Get a quote for eCommerce Solution",
		"Get a quote for SEO Solution",		
		"General question"		
		);
	return $reasonValue;
}
function getReasonName()
{
	$reasonName=array(1=>"Inquire our services",
		"Quote brand identity solution",
		"Quote marketing solution",
		"Quote Website solution",
		"Quote eCommerce Solution",
		"Quote SEO Solution",		
		"General Question"
		);
	return $reasonName;
}
?>